USE [LabDev]
GO

DROP TABLE IF EXISTS [dbo].[CatTipoCliente]
GO

/****** Object:  Table [dbo].[]    Created By: Mario Luevano ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CatTipoCliente](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TipoCliente] [varchar](50) NOT NULL,
 CONSTRAINT [PK_CatTipoCliente] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


